@host=127.0.0.1
@port=8888
@userId=1
@userName="jimmy"
@userPassword="123456"
@userCurrentPassword="654321"

@roleName="admin"
@roleId=1

@menuURL="/info"
@menuName="信息"
@menuId=1

### 创建分组
POST http://{{host}}:{{port}}/cmdb/create/objClassification
Content-Type: application/json

{
  "classification_id": "company",
  "classification_name": "公司"
}

### 查询分组
POST http://{{host}}:{{port}}/cmdb/list/objClassification
Content-Type: application/json

### 创建模型
POST http://{{host}}:{{port}}/cmdb/create/object
Content-Type: application/json

{
  "object_id": "development",
  "object_name": "开发部门",
  "classification_id": "company"
}

### 查询分组下的模型
POST http://{{host}}:{{port}}/cmdb/list/object
Content-Type: application/json

{
  "classification_id": "company"
}

### 创建属性
POST http://{{host}}:{{port}}/cmdb/create/objectAttr
Content-Type: application/json

{
  "object_id": "business",
  "property_id": "homeAddress",
  "property_name": "成员家庭地址",
  "property_type": "string"
}

### 查询模型下属性
POST http://{{host}}:{{port}}/cmdb/list/objectAttr
Content-Type: application/json

{
  "object_id": "business"
}

### 创建模型数据
POST http://{{host}}:{{port}}/cmdb/create/instance/object/business
Content-Type: application/json

{
  "homeAddress": "苏州吴中郭巷",
  "name": "jimmy",
  "age": "18"
}

### 查询模型数据
POST http://{{host}}:{{port}}/cmdb/list/instance/object/business
Content-Type: application/json